name: meta_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  dio: ^5.4.1
  video_player: ^2.8.3
  cloud_firestore: ^4.14.0
  uuid: ^4.4.0
  firebase_storage: ^11.6.0
  intl: ^0.19.0
  firebase_auth: ^4.16.0
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.4.0
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^5.0.2
  provider: ^6.1.1
#  emoji_picker_flutter: ^2.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
     - assets/logos/
     - assets/images/
     - assets/fonts/






  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

